Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false

Style/RegexpLiteral:
  Exclude:
    - '**/*.gemspec'
    - '**/Guardfile'

Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 15
Metrics/ClassLength:
  Exclude:
    - 'lib/guard/eslint/runner.rb'
Metrics/AbcSize:
  Exclude:
    - 'lib/guard/eslint/runner.rb'
Gemspec/RequiredRubyVersion:
  Include:
    - "2.4"